services:
  - type: web
    name: telegram-search-bot
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Vous devrez définir ceci manuellement
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: data
      mountPath: /tmp
      sizeGB: 1
